In [ ]:
"""
Como usar numpy
É um pacote para operações matemáticas
Bastante usado na criação de martizes
"""

In [3]:
# importa numpy é dá um apelido como np
import numpy as np

# array é como uma lista com restrições: do elemento é do mesmo tipo
a = np.array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
# [()] cria um array com duas dimensões
b = np.array([(1, 2, 3), (6, 1, 9), (4, 6, 5)])
print(b)

[[1 2 3]
 [6 1 9]
 [4 6 5]]


In [8]:
# cria uma matriz 4x3 com apenas zeros
c = np.zeros((4, 3))
print(c)
# cria uma matriz 3x4 com apenas zeros
c = np.ones((3, 4))
print(c)
# cria uma matriz identidade de lado 4
c = np.eye(4)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
print(b.max())
print(b.min())
print(b.sum()) # soma todos elementos
print(b.mean()) # média
print(b.std()) # desvio padrão

9
1
37
4.111111111111111
2.5141574442188355
